Excercise 4: Assuming no "taxation," compute the PageRanks a, b, and c of the three pages A, B, and C, using iteration, starting with the "0th" iteration where all three pages have rank a = b = c = 1. Compute as far as the 5th iteration, and also determine what the PageRanks are in the limit. Then, identify the true statement from the list below. null

![Alt text](Picture_1.png)

In [12]:
import numpy as np

m1 = np.matrix([[0.0,0.5,0.5,0.0], [1.0,0.0,.0,.0], [.0,.0,.0,1.0], [.0,.0,1.0,.0]]).T
beta = 0.7
w = 1.0 / 3.0

m2 = np.matrix([[w*2,w*2,w*2,w*2], [w,w,w,w], [0,0,0,0], [0,0,0,0]])



In [13]:
r = np.ones((m1.shape[0], 1)) / m1.shape[0]

for i in range(50):
    r = beta * np.dot(m1,r) + (1 - beta) * np.dot(m2, r)
    print(i + 1)
    print(r)

1
[[0.375 ]
 [0.1875]
 [0.2625]
 [0.175 ]]
2
[[0.33125]
 [0.23125]
 [0.25375]
 [0.18375]]
3
[[0.361875 ]
 [0.2159375]
 [0.2445625]
 [0.177625 ]]
4
[[0.35115625]
 [0.22665625]
 [0.25099375]
 [0.17119375]]
5
[[0.35865937]
 [0.22290469]
 [0.24274031]
 [0.17569562]]
6
[[0.35603328]
 [0.22553078]
 [0.24851772]
 [0.16991822]]
7
[[0.35787155]
 [0.22461165]
 [0.2435544 ]
 [0.1739624 ]]
8
[[0.35722815]
 [0.22525504]
 [0.24702872]
 [0.17048808]]
9
[[0.35767853]
 [0.22502985]
 [0.24437151]
 [0.17292011]]
10
[[0.3575209 ]
 [0.22518749]
 [0.24623156]
 [0.17106006]]
11
[[0.35763124]
 [0.22513231]
 [0.24487435]
 [0.17236209]]
12
[[0.35759262]
 [0.22517093]
 [0.2458244 ]
 [0.17141205]]
13
[[0.35761965]
 [0.22515742]
 [0.24514585]
 [0.17207708]]
14
[[0.35761019]
 [0.22516688]
 [0.24562083]
 [0.1716021 ]]
15
[[0.35761682]
 [0.22516357]
 [0.24528503]
 [0.17193458]]
16
[[0.3576145 ]
 [0.22516589]
 [0.24552009]
 [0.17169952]]
17
[[0.35761612]
 [0.22516507]
 [0.24535474]
 [0.17186407]]
18
[[0.35761555]
 [0.